//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutStat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class futebolEntities : DbContext
    {
        public futebolEntities()
            : base("name=futebolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<campeonato> campeonato { get; set; }
        public virtual DbSet<cidade> cidade { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<formacao> formacao { get; set; }
        public virtual DbSet<jogador> jogador { get; set; }
        public virtual DbSet<jogo> jogo { get; set; }
        public virtual DbSet<jogo_jogador> jogo_jogador { get; set; }
        public virtual DbSet<posicao> posicao { get; set; }
        public virtual DbSet<time> time { get; set; }
        public virtual DbSet<time_jogador> time_jogador { get; set; }
    }
}
