//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutStat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jogador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jogador()
        {
            this.time_jogador = new HashSet<time_jogador>();
            this.jogo_jogador = new HashSet<jogo_jogador>();
        }
    
        public int CD_JOGADOR { get; set; }
        public int CD_POSICAO { get; set; }
        public string DS_NOME { get; set; }
        public string DS_SOBRENOME { get; set; }
        public string DS_APELIDO { get; set; }
        public System.DateTime DT_NASCIMENTO { get; set; }
    
        public virtual posicao posicao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<time_jogador> time_jogador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jogo_jogador> jogo_jogador { get; set; }
    }
}
