//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutStat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jogo()
        {
            this.jogo_jogador = new HashSet<jogo_jogador>();
        }
    
        public int CD_JOGO { get; set; }
        public int CD_CAMPEONATO { get; set; }
        public int CD_TIME_MANDANTE { get; set; }
        public int CD_TIME_VISITANTE { get; set; }
        public Nullable<int> CD_FORMACAO_MANDANTE { get; set; }
        public Nullable<int> CD_FORMACAO_VISITANTE { get; set; }
        public int QT_GOL_MANDANTE { get; set; }
        public int QT_GOL_VISITANTE { get; set; }
        public string DS_FASE { get; set; }
        public System.DateTime DT_JOGO { get; set; }
        public int TP_RESULTADO { get; set; }
    
        public virtual campeonato campeonato { get; set; }
        public virtual formacao formacao { get; set; }
        public virtual formacao formacao1 { get; set; }
        public virtual time time { get; set; }
        public virtual time time1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jogo_jogador> jogo_jogador { get; set; }
    }
}
