//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutStat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jogo_jogador
    {
        public int CD_JOGO { get; set; }
        public int CD_JOGADOR { get; set; }
        public int NR_TEMPO_ENTRADA { get; set; }
        public int NR_MINUTO_ENTRADA { get; set; }
        public bool SN_SUBSTITUIDO { get; set; }
        public Nullable<int> NR_TEMPO_SAIDA { get; set; }
        public Nullable<int> NR_MINUTO_SAIDA { get; set; }
        public int QT_GOL { get; set; }
        public int QT_CARTAO_AMARELO { get; set; }
        public int QT_CARTAO_VERMELHO { get; set; }
        public int QT_FALTA_RECEBIDA { get; set; }
        public int QT_FALTA_FEITA { get; set; }
        public int QT_PASSE_CERTO { get; set; }
        public int QT_PASSE_ERRADO { get; set; }
        public int QT_ASSISTENCIA { get; set; }
    
        public virtual jogador jogador { get; set; }
        public virtual jogo jogo { get; set; }
    }
}
