//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FutStat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_jogador
    {
        public int CD_TIME { get; set; }
        public int CD_JOGADOR { get; set; }
        public System.DateTime DT_CHEGADA { get; set; }
        public Nullable<System.DateTime> DT_SAIDA { get; set; }
    
        public virtual jogador jogador { get; set; }
        public virtual time time { get; set; }
    }
}
